
var map = new ol.Map({
    target: 'map',
    renderer: 'canvas',
    layers: layersList,
    view: new ol.View({
        projection: 'EPSG:4326',
        constrainResolution: true,
        maxZoom: 28,
        minZoom: 1
    })
});

// EXACT LINES TO ADD IN qgis2web.js:
function togglePanel(contentId, arrowId) {
    var content = document.getElementById(contentId);
    var arrow = document.getElementById(arrowId);
    if (content.style.display === "none" || content.style.display === "") {
        content.style.display = "block";
        if (arrow) arrow.textContent = "▲";
    } else {
        content.style.display = "none";
        if (arrow) arrow.textContent = "▼";
    }
}

// EXACT LINES TO PASTE AFTER togglePanel IN qgis2web.js:

// --- Coordinate Jump Control ---
document.getElementById('coord-go-btn').addEventListener('click', function() {
    var inputVal = document.getElementById('coord-input').value.trim();
    if (!inputVal) return;

    var parts = inputVal.split(',').map(function(item) {
        return parseFloat(item.trim());
    });

    if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
        var lat = parts[0];
        var lon = parts[1];
        
        map.getView().animate({
            center: [lon, lat],
            zoom: 6,
            duration: 1000
        });
    } else {
        alert("Please enter valid coordinates in 'Lat, Lon' format (e.g., 15.5, 42.1)");
    }
});

// --- Layer Visibility & Opacity Controls ---
function setupLayerToggle(checkboxId, layerObj) {
    var chk = document.getElementById(checkboxId);
    if (chk && layerObj) {
        chk.addEventListener('change', function() {
            layerObj.setVisible(this.checked);
        });
    }
}

function setupLayerOpacity(sliderId, layerObj) {
    var slider = document.getElementById(sliderId);
    if (slider && layerObj) {
        slider.addEventListener('input', function() {
            layerObj.setOpacity(parseFloat(this.value));
        });
    }
}

	// Identify the primary base layer generated by qgis2web
	var basePaleoLayer = (typeof lyr_Map03_PALEOMAP_6min_Pliocene_5Ma_0 !== 'undefined') 
	    ? lyr_Map03_PALEOMAP_6min_Pliocene_5Ma_0 
	    : null;
	
	// Bind Land-Sea Mask controls to the base layer
	var chkLsm = document.getElementById('chk-lsm');
	if (chkLsm && basePaleoLayer) {
	    // Sync initial state
	    basePaleoLayer.setVisible(chkLsm.checked);
	    
	    chkLsm.addEventListener('change', function() {
	        basePaleoLayer.setVisible(this.checked);
	    });
	}
	
	var opLsm = document.getElementById('op-lsm');
	if (opLsm && basePaleoLayer) {
	    opLsm.addEventListener('input', function() {
	        basePaleoLayer.setOpacity(parseFloat(this.value));
	    });
	}
//initial view - epsg:4326 coordinates
map.getView().fit([-180.050000, -90.050000, 180.050000, 90.050000], map.getSize());

// 1. Standard 15-Degree Coordinate Graticule
var graticule = new ol.layer.Graticule({
    strokeStyle: new ol.style.Stroke({
        color: 'rgba(255, 255, 255, 0.25)',
        width: 1,
        lineDash: [4, 4]
    }),
    showLabels: true,
    intervals: [15]
});
graticule.setMap(map);

// 2. Five Major Latitude Lines (Equator, Tropics, Polar Circles)
var majorLatitudesSource = new ol.source.Vector();
var majorLats = [
    { name: 'Arctic Circle', lat: 66.5636 },
    { name: 'Tropic of Cancer', lat: 23.4364 },
    { name: 'Equator', lat: 0.0 },
    { name: 'Tropic of Capricorn', lat: -23.4364 },
    { name: 'Antarctic Circle', lat: -66.5636 }
];

majorLats.forEach(function(item) {
    var feature = new ol.Feature({
        geometry: new ol.geom.LineString([[-180, item.lat], [180, item.lat]]),
        name: item.name
    });
    majorLatitudesSource.addFeature(feature);
});

var majorLatitudesLayer = new ol.layer.Vector({
    source: majorLatitudesSource,
    style: function(feature) {
        var isEquator = feature.get('name') === 'Equator';
        return new ol.style.Style({
            stroke: new ol.style.Stroke({
                color: isEquator ? 'rgba(255, 215, 0, 0.85)' : 'rgba(255, 255, 255, 0.65)',
                width: isEquator ? 2 : 1.5,
                lineDash: isEquator ? null : [6, 4]
            })
        });
    }
});
map.addLayer(majorLatitudesLayer);

// 1. Mouse Coordinate Hover Display Control
var mousePosControl = new ol.control.MousePosition({
    coordinateFormat: function(coord) {
        return 'Lat: ' + coord[1].toFixed(4) + '°, Lon: ' + coord[0].toFixed(4) + '°';
    },
    projection: 'EPSG:4326'
});
map.addControl(mousePosControl);

// --- Independent Coordinate Pin Layer ---
var pinSource = new ol.source.Vector();
var pinLayer = new ol.layer.Vector({
    source: pinSource,
    style: new ol.style.Style({
        image: new ol.style.Circle({
            radius: 8,
            fill: new ol.style.Fill({ color: '#e74c3c' }),
            stroke: new ol.style.Stroke({ color: '#ffffff', width: 2 })
        })
    })
});

// Force pin to stay above ALL maps, raster overlays, and fossil vector layers
pinLayer.setZIndex(99999);
map.addLayer(pinLayer);

// --- Independent Coordinate Jump Execution ---
var coordBtn = document.getElementById('coord-go-btn');
if (coordBtn) {
    coordBtn.addEventListener('click', function(e) {
        e.preventDefault();
        e.stopPropagation();

        var inputVal = document.getElementById('coord-input').value.trim();
        if (!inputVal) return;

        var parts = inputVal.split(',').map(function(item) { 
            return parseFloat(item.trim()); 
        });

        if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
            var lat = parts[0];
            var lon = parts[1];
            var coords = [lon, lat];

            // Render pin independently
            pinSource.clear();
            var pinFeature = new ol.Feature({
                geometry: new ol.geom.Point(coords)
            });
            pinSource.addFeature(pinFeature);

            // Zoom map to target location
            map.getView().animate({ center: coords, zoom: 6, duration: 800 });
        } else {
            alert('Please enter coordinates in "Latitude, Longitude" format (e.g., 15.5, 42.1)');
        }
    });
}

// Link OpenLayers MousePosition to UI panel display
mousePosControl.setTarget(document.getElementById('coord-display'));

// Coordinate Jump execution
var coordBtn = document.getElementById('coord-go-btn');
if (coordBtn) {
    coordBtn.addEventListener('click', function() {
    var inputVal = document.getElementById('coord-input').value.trim();
    var parts = inputVal.split(',').map(function(item) { return parseFloat(item.trim()); });
    if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
        var lat = parts[0];
        var lon = parts[1];
        var coords = [lon, lat];
        pinSource.clear();
        var pinFeature = new ol.Feature({
            geometry: new ol.geom.Point(coords)
        });
        pinSource.addFeature(pinFeature);
        map.getView().animate({ center: coords, zoom: 5, duration: 800 });
    } else {
        alert('Please enter coordinates in "Latitude, Longitude" format (e.g., 15.5, 42.1)');
    }
    });
}

//change cursor
function pointerOnFeature(evt) {
    if (evt.dragging) {
        return;
    }
    var hasFeature = map.hasFeatureAtPixel(evt.pixel, {
        layerFilter: function(layer) {
            return layer && (layer.get("interactive"));
        }
    });
    map.getViewport().style.cursor = hasFeature ? "pointer" : "";
}
map.on('pointermove', pointerOnFeature);
function styleCursorMove() {
    map.on('pointerdrag', function() {
        map.getViewport().style.cursor = "move";
    });
    map.on('pointerup', function() {
        map.getViewport().style.cursor = "default";
    });
}
styleCursorMove();

////small screen definition
    var hasTouchScreen = map.getViewport().classList.contains('ol-touch');
    var isSmallScreen = window.innerWidth < 650;

////controls container

    //top left container
    var topLeftContainer = new ol.control.Control({
        element: (() => {
            var topLeftContainer = document.createElement('div');
            topLeftContainer.id = 'top-left-container';
            return topLeftContainer;
        })(),
    });
    map.addControl(topLeftContainer)

    //bottom left container
    var bottomLeftContainer = new ol.control.Control({
        element: (() => {
            var bottomLeftContainer = document.createElement('div');
            bottomLeftContainer.id = 'bottom-left-container';
            return bottomLeftContainer;
        })(),
    });
    map.addControl(bottomLeftContainer)
  
    //top right container
    var topRightContainer = new ol.control.Control({
        element: (() => {
            var topRightContainer = document.createElement('div');
            topRightContainer.id = 'top-right-container';
            return topRightContainer;
        })(),
    });
    map.addControl(topRightContainer)

    //bottom right container
    var bottomRightContainer = new ol.control.Control({
        element: (() => {
            var bottomRightContainer = document.createElement('div');
            bottomRightContainer.id = 'bottom-right-container';
            return bottomRightContainer;
        })(),
    });
    map.addControl(bottomRightContainer)

//popup
var container = document.getElementById('popup');
var content = document.getElementById('popup-content');
var closer = document.getElementById('popup-closer');
var sketch;

function stopMediaInPopup() {
    var mediaElements = container.querySelectorAll('audio, video');
    mediaElements.forEach(function(media) {
        media.pause();
        media.currentTime = 0;
    });
}
closer.onclick = function() {
    container.style.display = 'none';
    closer.blur();
    stopMediaInPopup();
    return false;
};
var overlayPopup = new ol.Overlay({
    element: container,
	autoPan: true
});
map.addOverlay(overlayPopup)
    
    
var NO_POPUP = 0
var ALL_FIELDS = 1

/**
 * Returns either NO_POPUP, ALL_FIELDS or the name of a single field to use for
 * a given layer
 * @param layerList {Array} List of ol.Layer instances
 * @param layer {ol.Layer} Layer to find field info about
 */
function getPopupFields(layerList, layer) {
    // Determine the index that the layer will have in the popupLayers Array,
    // if the layersList contains more items than popupLayers then we need to
    // adjust the index to take into account the base maps group
    var idx = layersList.indexOf(layer) - (layersList.length - popupLayers.length);
    return popupLayers[idx];
}

//highligth collection
var collection = new ol.Collection();
var featureOverlay = new ol.layer.Vector({
    map: map,
    source: new ol.source.Vector({
        features: collection,
        useSpatialIndex: false // optional, might improve performance
    }),
    style: [new ol.style.Style({
        stroke: new ol.style.Stroke({
            color: '#f00',
            width: 1
        }),
        fill: new ol.style.Fill({
            color: 'rgba(255,0,0,0.1)'
        }),
    })],
    updateWhileAnimating: true, // optional, for instant visual feedback
    updateWhileInteracting: true // optional, for instant visual feedback
});

var doHighlight = false;
var doHover = false;

function createPopupField(currentFeature, currentFeatureKeys, layer) {
    var popupText = '';
    for (var i = 0; i < currentFeatureKeys.length; i++) {
        if (currentFeatureKeys[i] != 'geometry' &&
            currentFeatureKeys[i] != 'layerObject' &&
            currentFeatureKeys[i] != 'idO' &&
            currentFeatureKeys[i] != '_mvtLayer_') {
            var popupField = '';
            if (layer.get('fieldLabels')[currentFeatureKeys[i]] == "hidden field") {
                continue;
            } else if (layer.get('fieldLabels')[currentFeatureKeys[i]] == "inline label - visible with data") {
                if (currentFeature.get(currentFeatureKeys[i]) == null) {
                    continue;
                }
            }
            if (layer.get('fieldLabels')[currentFeatureKeys[i]] == "inline label - always visible" ||
                layer.get('fieldLabels')[currentFeatureKeys[i]] == "inline label - visible with data") {
                popupField += '<th>' + layer.get('fieldAliases')[currentFeatureKeys[i]] + '</th><td>';
            } else {
                popupField += '<td colspan="2">';
            }
            if (layer.get('fieldLabels')[currentFeatureKeys[i]] == "header label - visible with data") {
                if (currentFeature.get(currentFeatureKeys[i]) == null) {
                    continue;
                }
            }
            if (layer.get('fieldLabels')[currentFeatureKeys[i]] == "header label - always visible" ||
                layer.get('fieldLabels')[currentFeatureKeys[i]] == "header label - visible with data") {
                popupField += '<strong>' + layer.get('fieldAliases')[currentFeatureKeys[i]] + '</strong><br />';
            }
            if (layer.get('fieldImages')[currentFeatureKeys[i]] != "ExternalResource") {
				popupField += (currentFeature.get(currentFeatureKeys[i]) != null ? autolinker.link(currentFeature.get(currentFeatureKeys[i]).toLocaleString()) + '</td>' : '');
			} else {
				var fieldValue = currentFeature.get(currentFeatureKeys[i]);
				if (/\.(gif|jpg|jpeg|tif|tiff|png|avif|webp|svg)$/i.test(fieldValue)) {
					popupField += (fieldValue != null ? '<img src="images/' + fieldValue.replace(/[\\\/:]/g, '_').trim() + '" /></td>' : '');
				} else if (/\.(mp4|webm|ogg|avi|mov|flv)$/i.test(fieldValue)) {
					popupField += (fieldValue != null ? '<video controls><source src="images/' + fieldValue.replace(/[\\\/:]/g, '_').trim() + '" type="video/mp4">Il tuo browser non supporta il tag video.</video></td>' : '');
				} else if (/\.(mp3|wav|ogg|aac|flac)$/i.test(fieldValue)) {
                    popupField += (fieldValue != null ? '<audio controls><source src="images/' + fieldValue.replace(/[\\\/:]/g, '_').trim() + '" type="audio/mpeg">Il tuo browser non supporta il tag audio.</audio></td>' : '');
                } else {
					popupField += (fieldValue != null ? autolinker.link(fieldValue.toLocaleString()) + '</td>' : '');
				}
			}
            popupText += '<tr>' + popupField + '</tr>';
        }
    }
    return popupText;
}

var highlight;
var autolinker = new Autolinker({truncate: {length: 30, location: 'smart'}});

function onPointerMove(evt) {
    if (!doHover && !doHighlight) {
        return;
    }
    var pixel = map.getEventPixel(evt.originalEvent);
    var coord = evt.coordinate;
    var currentFeature;
    var currentLayer;
    var currentFeatureKeys;
    var clusteredFeatures;
    var clusterLength;
    var popupText = '<ul>';

    // Collect all features and their layers at the pixel
    var featuresAndLayers = [];
    map.forEachFeatureAtPixel(pixel, function(feature, layer) {
        if (layer && feature instanceof ol.Feature && (layer.get("interactive") || layer.get("interactive") === undefined)) {
            featuresAndLayers.push({ feature, layer });
        }
    });

    // Iterate over the features and layers in reverse order
    for (var i = featuresAndLayers.length - 1; i >= 0; i--) {
        var feature = featuresAndLayers[i].feature;
        var layer = featuresAndLayers[i].layer;
        var doPopup = false;
        for (k in layer.get('fieldImages')) {
            if (layer.get('fieldImages')[k] != "Hidden") {
                doPopup = true;
            }
        }
        currentFeature = feature;
        currentLayer = layer;
        clusteredFeatures = feature.get("features");
        if (clusteredFeatures) {
            clusterLength = clusteredFeatures.length;
        }
        if (typeof clusteredFeatures !== "undefined") {
            if (doPopup) {
                for(var n=0; n<clusteredFeatures.length; n++) {
                    currentFeature = clusteredFeatures[n];
                    currentFeatureKeys = currentFeature.getKeys();
                    popupText += '<li><table>'
                    popupText += '<a>' + '<b>' + layer.get('popuplayertitle') + '</b>' + '</a>';
                    popupText += createPopupField(currentFeature, currentFeatureKeys, layer);
                    popupText += '</table></li>';    
                }
            }
        } else {
            currentFeatureKeys = currentFeature.getKeys();
            if (doPopup) {
                popupText += '<li><table>';
                popupText += '<a>' + '<b>' + layer.get('popuplayertitle') + '</b>' + '</a>';
                popupText += createPopupField(currentFeature, currentFeatureKeys, layer);
                popupText += '</table></li>';
            }
        }
    }

    if (popupText == '<ul>') {
        popupText = '';
    } else {
        popupText += '</ul>';
    }
    
	if (doHighlight) {
        if (currentFeature !== highlight) {
            if (highlight) {
                featureOverlay.getSource().removeFeature(highlight);
            }
            if (currentFeature) {
                var featureStyle
                if (typeof clusteredFeatures == "undefined") {
					var style = currentLayer.getStyle();
					var styleFunction = typeof style === 'function' ? style : function() { return style; };
					featureStyle = styleFunction(currentFeature)[0];
				} else {
					featureStyle = currentLayer.getStyle().toString();
				}

                if (currentFeature.getGeometry().getType() == 'Point' || currentFeature.getGeometry().getType() == 'MultiPoint') {
                    var radius
					if (typeof clusteredFeatures == "undefined") {
						radius = featureStyle.getImage().getRadius();
					} else {
						radius = parseFloat(featureStyle.split('radius')[1].split(' ')[1]) + clusterLength;
					}

                    highlightStyle = new ol.style.Style({
                        image: new ol.style.Circle({
                            fill: new ol.style.Fill({
                                color: "rgba(255, 255, 0, 1.00)"
                            }),
                            radius: radius
                        })
                    })
                } else if (currentFeature.getGeometry().getType() == 'LineString' || currentFeature.getGeometry().getType() == 'MultiLineString') {

                    var featureWidth = featureStyle.getStroke().getWidth();

                    highlightStyle = new ol.style.Style({
                        stroke: new ol.style.Stroke({
                            color: 'rgba(255, 255, 0, 1.00)',
                            lineDash: null,
                            width: featureWidth
                        })
                    });

                } else {
                    highlightStyle = new ol.style.Style({
                        fill: new ol.style.Fill({
                            color: 'rgba(255, 255, 0, 1.00)'
                        })
                    })
                }
                featureOverlay.getSource().addFeature(currentFeature);
                featureOverlay.setStyle(highlightStyle);
            }
            highlight = currentFeature;
        }
    }

    if (doHover) {
        if (popupText) {
			content.innerHTML = popupText;
            container.style.display = 'block';
            overlayPopup.setPosition(coord);
        } else {
            container.style.display = 'none';
            closer.blur();
        }
    }
};

map.on('pointermove', onPointerMove);

var popupContent = '';
var popupCoord = null;
var featuresPopupActive = false;

function updatePopup() {
    if (popupContent) {
        content.innerHTML = popupContent;
        container.style.display = 'block';
		overlayPopup.setPosition(popupCoord);
    } else {
        container.style.display = 'none';
        closer.blur();
        stopMediaInPopup();
    }
} 

function onSingleClickFeatures(evt) {
    if (doHover || sketch) {
        return;
    }
    if (!featuresPopupActive) {
        featuresPopupActive = true;
    }
    var pixel = map.getEventPixel(evt.originalEvent);
    var coord = evt.coordinate;
    var currentFeature;
    var currentFeatureKeys;
    var clusteredFeatures;
    var popupText = '<ul>';
    
    map.forEachFeatureAtPixel(pixel, function(feature, layer) {
        if (layer && feature instanceof ol.Feature && (layer.get("interactive") || layer.get("interactive") === undefined)) {
            var doPopup = false;
            for (var k in layer.get('fieldImages')) {
                if (layer.get('fieldImages')[k] !== "Hidden") {
                    doPopup = true;
                }
            }
            currentFeature = feature;
            clusteredFeatures = feature.get("features");
            if (typeof clusteredFeatures !== "undefined") {
                if (doPopup) {
                    for(var n = 0; n < clusteredFeatures.length; n++) {
                        currentFeature = clusteredFeatures[n];
                        currentFeatureKeys = currentFeature.getKeys();
                        popupText += '<li><table>';
                        popupText += '<a><b>' + layer.get('popuplayertitle') + '</b></a>';
                        popupText += createPopupField(currentFeature, currentFeatureKeys, layer);
                        popupText += '</table></li>';    
                    }
                }
            } else {
                currentFeatureKeys = currentFeature.getKeys();
                if (doPopup) {
                    popupText += '<li><table>';
                    popupText += '<a><b>' + layer.get('popuplayertitle') + '</b></a>';
                    popupText += createPopupField(currentFeature, currentFeatureKeys, layer);
                    popupText += '</table>';
                }
            }
        }
    });
    if (popupText === '<ul>') {
        popupText = '';
    } else {
        popupText += '</ul>';
    }
	
	popupContent = popupText;
    popupCoord = coord;
    updatePopup();
}

function onSingleClickWMS(evt) {
    if (doHover || sketch) {
        return;
    }
    if (!featuresPopupActive) {
        popupContent = '';
    }
    var coord = evt.coordinate;
    var viewProjection = map.getView().getProjection();
    var viewResolution = map.getView().getResolution();

    for (var i = 0; i < wms_layers.length; i++) {
        if (wms_layers[i][1] && wms_layers[i][0].getVisible()) {
            var url = wms_layers[i][0].getSource().getFeatureInfoUrl(
                evt.coordinate, viewResolution, viewProjection, {
                    'INFO_FORMAT': 'text/html',
                });
            if (url) {
                const wmsTitle = wms_layers[i][0].get('popuplayertitle');
                var ldsRoller = '<div class="roller-switcher" style="height: 25px; width: 25px;"></div>';

                popupCoord = coord;
                popupContent += ldsRoller;
                updatePopup();

                var timeoutPromise = new Promise((resolve, reject) => {
                    setTimeout(() => {
                        reject(new Error('Timeout exceeded'));
                    }, 5000); // (5 second)
                });

                // Function to try fetch with different option
                function tryFetch(urls) {
                    if (urls.length === 0) {
                        return Promise.reject(new Error('All fetch attempts failed'));
                    }
                    return fetch(urls[0])
                        .then((response) => {
                            if (response.ok) {
                                return response.text();
                            } else {
                                throw new Error('Fetch failed');
                            }
                        })
                        .catch(() => tryFetch(urls.slice(1))); // Try next URL
                }

                // List of URLs to try
                // The first URL is the original, the second is the encoded version, and the third is the proxy
                const urlsToTry = [
                    url,
                    encodeURIComponent(url),
                    'https://api.allorigins.win/raw?url=' + encodeURIComponent(url)
                ];

                Promise.race([tryFetch(urlsToTry), timeoutPromise])
                    .then((html) => {
                        if (html.indexOf('<table') !== -1) {
                            popupContent += '<a><b>' + wmsTitle + '</b></a>';
                            popupContent += html + '<p></p>';
                            updatePopup();
                        }
                    })
                    .finally(() => {
                        setTimeout(() => {
                            var loaderIcon = document.querySelector('.roller-switcher');
                            if (loaderIcon) loaderIcon.remove();
                        }, 500); // (0.5 second)
                    });
            }
        }
    }
}

map.on('singleclick', onSingleClickFeatures);
map.on('singleclick', onSingleClickWMS);

//get container
var topLeftContainerDiv = document.getElementById('top-left-container')
var bottomLeftContainerDiv = document.getElementById('bottom-left-container')
var topRightContainerDiv = document.getElementById('top-right-container')
var bottomRightContainerDiv = document.getElementById('bottom-right-container')

//title

//abstract


//geolocate



//measurement





//geocoder


//layer search


//scalebar


//layerswitcher






//attribution
var bottomAttribution = new ol.control.Attribution({
  collapsible: false,
  collapsed: false,
  className: 'bottom-attribution'
});
map.addControl(bottomAttribution);

map.once('rendercomplete', function() {
  var bottomAttributionUl = bottomAttribution.element.querySelector('ul');
  if (bottomAttributionUl) {
    var layerAttrs = Array.from(bottomAttributionUl.querySelectorAll('li'))
      .map(function(li) { return li.innerHTML.trim(); }).filter(Boolean);
    var attribHtml = `
    <a href="https://github.com/qgis2web/qgis2web">qgis2web</a> &middot;
    <a href="https://openlayers.org/">OpenLayers</a> &middot;
    <a href="https://qgis.org/">QGIS</a>`;
    if (layerAttrs.length > 0) { attribHtml += ' &nbsp;|&nbsp; ' + layerAttrs.join(', '); }
    bottomAttributionUl.innerHTML = '<li>' + attribHtml + '</li>';
  }
});


// Disable "popup on hover" or "highlight on hover" if ol-control mouseover
var preDoHover = doHover;
var preDoHighlight = doHighlight;
var isPopupAllActive = false;
document.addEventListener('DOMContentLoaded', function() {
	if (doHover || doHighlight) {
		var controlElements = document.getElementsByClassName('ol-control');
		for (var i = 0; i < controlElements.length; i++) {
			controlElements[i].addEventListener('mouseover', function() { 
				doHover = false;
				doHighlight = false;
			});
			controlElements[i].addEventListener('mouseout', function() {
				doHover = preDoHover;
				if (isPopupAllActive) { return }
				doHighlight = preDoHighlight;
			});
		}
	}
});


//move controls inside containers, in order
    //zoom
    var zoomControl = document.getElementsByClassName('ol-zoom')[0];
    if (zoomControl) {
        topLeftContainerDiv.appendChild(zoomControl);
    }
    //geolocate
    if (typeof geolocateControl !== 'undefined') {
        topLeftContainerDiv.appendChild(geolocateControl);
    }
    //measure
    if (typeof measureControl !== 'undefined') {
        topLeftContainerDiv.appendChild(measureControl);
    }
    //geocoder
    var searchbar = document.getElementsByClassName('photon-geocoder-autocomplete ol-unselectable ol-control')[0];
    if (searchbar) {
        topLeftContainerDiv.appendChild(searchbar);
    }
    //search layer
    var searchLayerControl = document.getElementsByClassName('search-layer')[0];
    if (searchLayerControl) {
        topLeftContainerDiv.appendChild(searchLayerControl);
    }
    //scale line
    var scaleLineControl = document.getElementsByClassName('ol-scale-line')[0];
    if (scaleLineControl) {
        scaleLineControl.className += ' ol-control';
        bottomLeftContainerDiv.appendChild(scaleLineControl);
    }
    //attribution
    var attributionControl = document.getElementsByClassName('bottom-attribution')[0];
    if (attributionControl) {
        bottomRightContainerDiv.appendChild(attributionControl);
    }

	// PBDB Pliocene Fossil Occurrences Layer
	var pbdbVectorSource = new ol.source.Vector({
	    url: './layers/pbdb_pliocene.geojson',
	    format: new ol.format.GeoJSON()
	});
	
	var pbdbVectorLayer = new ol.layer.Vector({
	    visible: false,
		source: pbdbVectorSource,
	    style: new ol.style.Style({
	        image: new ol.style.Circle({
	            radius: 5,
	            fill: new ol.style.Fill({ color: '#8e44ad' }),
	            stroke: new ol.style.Stroke({ color: '#ffffff', width: 1 })
	        })
	    }),
	    title: 'Pliocene Fossil Occurrences'
	});
	map.addLayer(pbdbVectorLayer);
	pbdbVectorLayer.setZIndex(9999);

	// Custom Fossil Popup Overlay
	var container = document.getElementById('fossil-popup');
	var content = document.getElementById('fossil-popup-content');
	var closer = document.getElementById('fossil-popup-closer');
	
	var overlay = new ol.Overlay({
	    element: container,
	    autoPan: true,
	    autoPanAnimation: { duration: 250 }
	});
	map.addOverlay(overlay);
	
	closer.onclick = function() {
	    overlay.setPosition(undefined);
	    closer.blur();
	    return false;
	};
	
	// Pointer cursor on hover
	map.on('pointermove', function(e) {
	    var hit = map.hasFeatureAtPixel(e.pixel, { hitTolerance: 5 });
	    map.getTargetElement().style.cursor = hit ? 'pointer' : '';
	});
	
	// Click handler to render attribute text
	map.on('singleclick', function(evt) {
	    var feature = map.forEachFeatureAtPixel(evt.pixel, function(feat) {
	        return feat;
	    }, { hitTolerance: 5 });
	
	    if (feature) {
	        var props = feature.getProperties();
	        var keys = Object.keys(props).filter(function(k) { return k !== 'geometry'; });
	        var bodyText = '';
	
	        if (keys.length > 0) {
	            keys.forEach(function(key) {
	                bodyText += '<b>' + key + ':</b> ' + props[key] + '<br>';
	            });
	        } else {
	            bodyText = '<em>No attribute details found.</em>';
	        }
	
	        content.innerHTML = bodyText;
	        overlay.setPosition(evt.coordinate);
	    } else {
	        overlay.setPosition(undefined);
	    }
	});

	// --- GeoTIFF Layer Initialization ---

	// --- GeoTIFF Layer Initialization ---
	var lsmLayer = new ol.layer.WebGLTile({
	  visible: false,
	  opacity: 1.0,
	  source: new ol.source.GeoTIFF({
	    sources: [{ url: 'layers/lsm.tif' }]
	  })
	});
	
	var topoLayer = new ol.layer.WebGLTile({
	  visible: false,
	  opacity: 0.8,
	  source: new ol.source.GeoTIFF({
	    sources: [{ url: 'layers/topo.tif' }]
	  })
	});
	
	var sstLayer = new ol.layer.WebGLTile({
	  visible: false,
	  opacity: 0.8,
	  source: new ol.source.GeoTIFF({
	    sources: [{ url: 'layers/sst.tif' }]
	  })
	});
	
	var biomeLayer = new ol.layer.WebGLTile({
	  visible: false,
	  opacity: 0.8,
	  source: new ol.source.GeoTIFF({
	    sources: [{ url: 'layers/mbiome.tif' }]
	  })
	});
	
	var soilLayer = new ol.layer.WebGLTile({
	  visible: false,
	  opacity: 0.8,
	  source: new ol.source.GeoTIFF({
	    sources: [{ url: 'layers/soil.tif' }]
	  })
	});
	
	var iceLayer = new ol.layer.WebGLTile({
	  visible: false,
	  opacity: 0.9,
	  source: new ol.source.GeoTIFF({
	    sources: [{ url: 'layers/icemask.tif' }]
	  })
	});
	
	var lakeLayer = new ol.layer.WebGLTile({
	  visible: false,
	  opacity: 0.9,
	  source: new ol.source.GeoTIFF({
	    sources: [{ url: 'layers/lake.tif' }]
	  })
	});
	
	// Add overlay layers to map
	map.addLayer(lsmLayer);
	map.addLayer(topoLayer);
	map.addLayer(sstLayer);
	map.addLayer(biomeLayer);
	map.addLayer(soilLayer);
	map.addLayer(iceLayer);
	map.addLayer(lakeLayer);

	// Helper function for UI bindings
	function connectLayer(chkId, sliderId, layer) {
	    if (!layer) return;
	    var chk = document.getElementById(chkId);
	    if (chk) {
	        layer.setVisible(chk.checked);
	        chk.addEventListener('change', function() {
	            layer.setVisible(this.checked);
	        });
	    }
	    var slider = document.getElementById(sliderId);
	    if (slider) {
	        slider.addEventListener('input', function() {
	            layer.setOpacity(parseFloat(this.value));
	        });
	    }
	}

	// Connect UI Controls directly to WebGLTile GeoTIFF layers
	connectLayer('chk-lsm', 'op-lsm', lsmLayer);
	connectLayer('chk-topo', 'op-topo', topoLayer);
	connectLayer('chk-sst', 'op-sst', sstLayer);
	connectLayer('chk-biome', 'op-biome', biomeLayer);
	connectLayer('chk-soil', 'op-soil', soilLayer);
	connectLayer('chk-ice', 'op-ice', iceLayer);
	connectLayer('chk-lake', 'op-lake', lakeLayer);

	// --- Fix 2: Panel Toggle Handler ---
	function togglePanel(contentId, arrowId) {
	  var content = document.getElementById(contentId);
	  var arrow = document.getElementById(arrowId);
	  if (content.classList.contains('active')) {
	    content.classList.remove('active');
	    arrow.textContent = '▼';
	  } else {
	    content.classList.add('active');
	    arrow.textContent = '▲';
	  }
	}
	
	// --- Fix 4: Click Map to Pop Out Coordinates with Copy Button ---
	var popupElement = document.getElementById('click-coord-popup');
	var popupOverlay = new ol.Overlay({
	  element: popupElement,
	  positioning: 'bottom-center',
	  stopEvent: true,
	  offset: [0, -10]
	});
	map.addOverlay(popupOverlay);
	
	var currentClickedCoords = "";
	
	// EXACT LINES TO REPLACE WITH
	map.on('singleclick', function (evt) {
	  var fossilChk = document.getElementById('chk-fossils');
	  var fossilsVisible = fossilChk ? fossilChk.checked : false;
	  
	  var featureFound = false;
	  if (fossilsVisible) {
	    featureFound = map.forEachFeatureAtPixel(evt.pixel, function (feature) {
	      return true;
	    });
	  }
	
	  if (!featureFound) {
	    var mapProjection = map.getView().getProjection();
	    var geoCoord = ol.proj.transform(evt.coordinate, mapProjection, 'EPSG:4326');
	    var lon = geoCoord[0].toFixed(4);
	    var lat = geoCoord[1].toFixed(4);
	    
	    currentClickedCoords = lat + "° N, " + lon + "° E";
	    if (lat < 0) currentClickedCoords = Math.abs(lat) + "° S, " + (lon < 0 ? Math.abs(lon) + "° W" : lon + "° E");
	    else if (lon < 0) currentClickedCoords = lat + "° N, " + Math.abs(lon) + "° W";
	
	    document.getElementById('popup-coord-text').innerText = lat + ", " + lon;
	    currentClickedCoords = lat + ", " + lon;
	    
	    popupElement.style.display = 'flex';
	    popupOverlay.setPosition(evt.coordinate);

	    // Automatically hide the popup after 5 seconds
	    if (window.coordPopupTimeout) {
	        clearTimeout(window.coordPopupTimeout);
	    }
	    window.coordPopupTimeout = setTimeout(function() {
	        popupElement.style.display = 'none';
	        popupOverlay.setPosition(undefined);
	    }, 5000);
	  }
	});
	
	// Copy Function
	function copyCoordinates() {
	  if (currentClickedCoords) {
	    navigator.clipboard.writeText(currentClickedCoords).then(function() {
	      var copyBtn = document.querySelector('.coord-copy-btn');
	      copyBtn.innerText = "Copied!";
	      setTimeout(function() { copyBtn.innerText = "Copy"; }, 1500);
	    });
	  }
	}
	
	// Fossil Occurrences Toggle (Targets ONLY pbdbVectorLayer)
	var fossilChk = document.getElementById('chk-fossils');
	if (fossilChk) {
	  fossilChk.addEventListener('change', function(e) {
	    if (typeof pbdbVectorLayer !== 'undefined') {
	        pbdbVectorLayer.setVisible(e.target.checked);
	    }
	  });
	}

	// togglePanel Function
	function togglePanel(contentId, arrowId) {
	    var content = document.getElementById(contentId);
	    var arrow = document.getElementById(arrowId);
	    if (content.style.display === "none" || content.style.display === "") {
	        content.style.display = "block";
	        if (arrow) arrow.textContent = "▲";
	    } else {
	        content.style.display = "none";
	        if (arrow) arrow.textContent = "▼";
	    }
	}
	
	// --- 3. Dynamic PBDB Fossil Layer ---
	var fossilSource = new ol.source.Vector();
	var pbdbVectorLayer = new ol.layer.Vector({
	    source: fossilSource,
	    style: new ol.style.Style({
	        image: new ol.style.Circle({
	            radius: 5,
	            fill: new ol.style.Fill({ color: '#e67e22' }),
	            stroke: new ol.style.Stroke({ color: '#2c3e50', width: 1 })
	        })
	    })
	});
	map.addLayer(pbdbVectorLayer);
	
	// --- Unified Self-Contained PBDB Vector Layer & Fetch ---
	window.pbdbSource = new ol.source.Vector();

	window.pbdbVectorLayer = new ol.layer.Vector({
	    source: window.pbdbSource,
	    visible: false,
	    style: new ol.style.Style({
	        image: new ol.style.Circle({
	            radius: 5,
	            fill: new ol.style.Fill({ color: '#8e44ad' }),
	            stroke: new ol.style.Stroke({ color: '#ffffff', width: 1 })
	        })
	    })
	});
	map.addLayer(window.pbdbVectorLayer);
	window.pbdbVectorLayer.setZIndex(999);

	// Toggle Listener
	var fossilChk = document.getElementById('chk-fossils');
	if (fossilChk) {
	    fossilChk.addEventListener('change', function(e) {
	        window.pbdbVectorLayer.setVisible(e.target.checked);
	    });
	}

	// Helper functions for loading visual
	function showSpinner(msg) {
	    var sp = document.getElementById('loading-spinner');
	    var txt = document.getElementById('spinner-text');
	    if (sp && txt) { txt.innerText = msg; sp.style.display = 'block'; }
	}
	function hideSpinner() {
	    var sp = document.getElementById('loading-spinner');
	    if (sp) { sp.style.display = 'none'; }
	}

	// Fetch Data Directly into Window Source
	showSpinner('Fetching Fossils');
	fetch('https://paleobiodb.org/data1.2/occs/list.json?interval=Pliocene&show=coords,ident,attr')
	    .then(function(res) { return res.json(); })
	    .then(function(data) {
	        if (data && data.records) {
	            var features = [];
	            for (var i = 0; i < data.records.length; i++) {
	                var rec = data.records[i];
	                if (rec.lng !== undefined && rec.lat !== undefined) {
	                    var feat = new ol.Feature({
	                        geometry: new ol.geom.Point([rec.lng, rec.lat]),
	                        isFossil: true,
	                        tna: rec.tna || rec.nam || rec.tgn || 'Fossil Occurrence',
	                        oid: rec.oid || rec.occ_no || rec.cid || 'N/A'
	                    });
	                    features.push(feat);
	                }
	            }
	            window.pbdbSource.addFeatures(features);
	            if (fossilChk) {
	                window.pbdbVectorLayer.setVisible(fossilChk.checked);
	            }
	        }
	        hideSpinner();
	    })
	    .catch(function(err) {
	        console.error('PBDB Load Error:', err);
	        hideSpinner();
	    });

// --- Drag-Aware Pointer Handler for Touch and Desktop ---
var dragStartPixel = null;

map.getViewport().addEventListener('pointerdown', function(e) {
    dragStartPixel = [e.clientX, e.clientY];
});

map.getViewport().addEventListener('pointerup', function(e) {
    if (!dragStartPixel) return;

    // Calculate displacement to separate panning from tapping
    var deltaX = Math.abs(e.clientX - dragStartPixel[0]);
    var deltaY = Math.abs(e.clientY - dragStartPixel[1]);
    dragStartPixel = null;

    // If pointer moved more than 6px, treat as a map drag/pan and ignore click popup
    if (deltaX > 6 || deltaY > 6) return;

    var pixel = map.getEventPixel(e);
    var coord = map.getCoordinateFromPixel(pixel);
    if (!coord) return;

    var popupTextElem = document.getElementById('popup-coord-text');
    var popupElem = document.getElementById('popup');
    var clickedFeature = null;

    map.forEachFeatureAtPixel(pixel, function(feature) {
        if (feature && (feature.get('tna') || feature.get('isFossil'))) {
            clickedFeature = feature;
            return true;
        }
    }, { hitTolerance: 10 });

    if (clickedFeature) {
        var taxonName = clickedFeature.get('tna') || clickedFeature.get('nam') || 'Fossil Occurrence';
        var recordId = clickedFeature.get('oid') || clickedFeature.get('occ_no') || 'N/A';
        var lat = coord[1].toFixed(4);
        var lon = coord[0].toFixed(4);

        if (popupTextElem) {
            popupTextElem.innerHTML = '<b>' + taxonName + '</b><br>ID: ' + recordId + '<br>Coords: ' + lat + ', ' + lon;
        }
    } else {
        var lon = coord[0].toFixed(4);
        var lat = coord[1].toFixed(4);
        if (popupTextElem) {
            popupTextElem.innerText = lat + ", " + lon;
        }
    }

    if (popupOverlay) popupOverlay.setPosition(coord);
    if (popupElem) popupElem.style.display = 'flex';

    if (window.coordPopupTimeout) clearTimeout(window.coordPopupTimeout);
    window.coordPopupTimeout = setTimeout(function() {
        if (popupElem) popupElem.style.display = 'none';
        if (popupOverlay) popupOverlay.setPosition(undefined);
    }, 5000);
});
